title: Voice Clone
type: community
group: Virtual Huamn
image: /static/templates/voice-clone.jpg
details: <h1>Label exact products on the shelves</h1>
config: |
  <View>
    <Header value="Input Audio" />
    <Audio name="audio_1" value="$audio" zoom="true" hotkey="ctrl+enter" />

    <Header value="Generated Audio" />
    <Audio name="audio" value="$audio_url"/>

    <Rating name="rating" toName="video" maxRating="10" icon="star" size="medium" />
  </View>
 
