title: Detect Anything
type: community
group: Visual Solutions
image: /static/templates/inventory-tracking.png
details: <h1>Recognize large numbers of products using vector database</h1>
config: |
  <View>
    <Image name="image" value="$lspr"/>
    <Style>
      .lsf-main-content.lsf-requesting .prompt::before { content: ' loading...'; color: #808080; }
    </Style>
    <View className="prompt">
      <Header value="Provide prompt" />
      <TextArea name="prompt" toName="image" editable="true" rows="2" maxSubmissions="1" showSubmitButton="true"/>
    </View>
    <RectangleLabels name="label" toName="image"/>
  
  </View>