title: LLM Finetuning
type: community
group: LLM Solutions
order: 10000
image: /static/templates/rlhf.jpeg
details: <h1>Collecting data for LLM supervised fine-tuning</h1>
config: |
  <View style="display: flex;">
    <View style="width: 600px; padding-left: 1em; margin-right: 1em; background: #ffffff; border-radius: 1px">  
    <Paragraphs name="dialogue" value="$dialogue" layout="dialogue" textKey="content" nameKey="role"/>
    <Header value="User prompt:"/>
      <View className="prompt">
          <TextArea name="prompt" toName="dialogue" rows="4" editable="true" maxSubmissions="1" showSubmitButton="false"/>
      </View>
      <Header value="Bot answer:"/>
      <TextArea name="response" toName="dialogue" rows="4" editable="true" smart="false" maxSubmissions="1" showSubmitButton="false"/>
    </View>
  </View>