apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          resources:
            requests:
              memory: 40Mi
              cpu: 10m
            limits:
              memory: 400Mi
              cpu: 100m
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-main
  labels:
    app.kubernetes.io/component: frontend-main
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /main/$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-image-tool
  labels:
    app.kubernetes.io/component: frontend-image-tool
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /image-tool/$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /tool/image(/|$)(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-pc-tool
  labels:
    app.kubernetes.io/component: frontend-pc-tool
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /pc-tool/$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /tool/pc(/|$)(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-text-tool
  labels:
    app.kubernetes.io/component: frontend-text-tool
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /text-tool/$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /tool/text(/|$)(.*)
            pathType: Prefix
