title: Create From Website
type: community
group: Knowledge Creation
image: /static/templates/websites.png
details: <h1>Label exact products on the shelves</h1>
config: |
  <View>
    <View>
      <Labels name="label" toName="text">
        <Label value="PER" background="red"/>
        <Label value="ORG" background="darkorange"/>
        <Label value="LOC" background="orange"/>
        <Label value="MISC" background="green"/>
      </Labels>
      <Taxonomy name="taxonomy" toName="text">
        <Choice value="Archaea" />
        <Choice value="Bacteria" />
        <Choice value="Eukarya">
          <Choice value="Human" />
          <Choice value="Opossum" />
          <Choice value="Extraterrestrial" />
        </Choice>
      </Taxonomy>
      <Relations>
        <Relation value="org:founded_by"/>
        <Relation value="org:founded"/>
      </Relations>
      <Labels name="label" toName="text">
        <Label value="Organization" background="orange"/>
        <Label value="Person" background="green"/>
        <Label value="Datetime" background="blue"/>
      </Labels>
    </View>
    <Header value="Search request" size="5"/> 
    <Text name="text" value="$text"/>
    <Header value="Search Website" size="5"/> 
    <Text name="text" value="$text"/>
  
    <Header value="Generated responses" size="5"/> 
    <View className="dynamic_choices">
      <Choices name="dynamic_choices" toName="text" selection="checkbox" value="$options" layout="vertical" choice="multiple" allownested="true"/>
    </View>
    
    <Style>
    .searchresultsarea {
      margin-left: 10px;
      font-family: 'Arial';
    }
    .searchresult {
      margin-left: 8px;
    }
    .searchresult h2 {
      font-size: 19px;
      line-height: 18px;
      font-weight: normal;
      color: rgb(29, 1, 189);
      margin-bottom: 0px;
      margin-top: 25px;
    }
    .searchresult a {
      font-size: 14px;
      line-height: 14px;
      color: green;
      margin-bottom: 0px;
    }
    .searchresult button {
      font-size: 10px;
      line-height: 14px;
      color: green;
      margin-bottom: 0px;
      padding: 0px;
      border-width: 0px;
      background-color: white;
    }
    </Style>
  </View>

