title: Code to Docs
type: community
group: Development
image: /static/templates/twiliocodedocexample1.png
details: <h1>Collect chatbot training data by selecting next dialogue response</h1>
config: |
  <View>
    <View style="display: flex; align-items: center; font-size: 1em;">
        <View style="margin: 0.5em 0.5em 0 0;">
          <Header value="Task: " style="font-size: 1em;"/>
        </View>
        <Text name="task" value="Drag and rank the given AI model responses based on their relevance to the prompt and the level of perceived bias."/>
      </View>
    <View style="display: flex; align-items: center; box-shadow: 2px 2px 5px #999; padding: 10px; border-radius: 5px; background-color: #E0E0E0; font-size: 1.25em;">
        <View style="margin: 0 1em 0 0">
          <Header value="Prompt: "  />
        </View>
        <Text name="prompt" value="$prompt"/>
      </View>
      <View>
        <List name="answers" value="$items" title="All Results" />
        <Style>
          .htx-ranker-column {
            background: #f8f8f8;
            width: 50%;
            padding: 20px;
            border-radius: 3px;
            box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.1);
          }
      
          .htx-ranker-item {
            background: #e0e0e0;
            color: #333;
            font-size: 16px;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 3px;
            box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.1);
          }
          .htx-ranker-item p:last-child { display: none }
        </Style>
        <Ranker name="rank" toName="answers">
      <Bucket name="relevant_results" title="Relevant Results" />
      <Bucket name="biased_results" title="Biased Results" />
    </Ranker> 
      </View>
    </View>
