title: LLM
type: community
group: Virtual Huamn
image: /static/templates/response-selection.png
details: <h1>Collect chatbot training data by selecting next dialogue response</h1>
config: |
  <View className="root">
      <Style>
          <!-- Different CSS styles for the prompt and the answer input -->
      </Style>
      <View className="container">
          <View className="prompt">
              <Text name="prompt" value="$prompt"/>
          </View>
          <View className="answer-input">
              <TextArea name="instruction" toName="prompt"
                        maxSubmissions="1" required="true"
                        requiredMessage="You must provide the response to the prompt"
                        placeholder="Type your answer here..."
                        rows="10"
              />
          </View>
      </View>
  </View>

