title: Video Understanding
type: community
group: Visual Solutions
image: /static/templates/video-timeline-segmentation.png
details: <h1>Video captioning</h1>
config: |
  <View>
    <Style>
        .lsf-main-content.lsf-requesting .prompt::before { content: ' loading...'; color: #808080; }
    </Style>

    <Video name="video" value="$video_url" sync="audio"/>
    <Audio name="audio" value="$video_url" sync="video" speed="false"/>

    <Header value="User prompt:"/>
    <TextArea name="prompt" toName="video" rows="4" editable="true" maxSubmissions="1" showSubmitButton="false"/>
    <Header value="Bot answer:"/>
    <TextArea name="response" toName="video" rows="4" editable="true" maxSubmissions="1" showSubmitButton="false"/>

  </View>
