title: Document Analysis
type: community
group: Visual Solutions
order: 10000
image: /static/templates/doc.jpg
details: <h1>Extract document information from images</h1>
config: |
  <View>    
    <Choices name="choices" choice="single-radio" toName="image" showInline="true">
        <Choice value="Recipt"/>
        <Choice value="Business Card"/>
    </Choices>
    <Image name="image" value="$doc" zoom="true" zoomControl="false"
          rotateControl="true" width="100%" height="100%"
          maxHeight="auto" maxWidth="auto"/>
    
    <RectangleLabels name="bbox" toName="image" strokeWidth="1" smart="true">
        <Label value="text" background="green"/>
        <Label value="table" background="blue"/>
        <Label value="title" background="red"/>
        <Label value="figure" background="yellow"/>
    </RectangleLabels>

    <TextArea name="transcription" toName="image" 
      editable="true" perRegion="true" required="true" 
      maxSubmissions="1" rows="5" placeholder="Recognized Text" 
      displayMode="region-list"/>
    
    <Table name="table" toName="image" value="$item"/>
  </View>