title: Video Generation
type: community
group: Virtual Huamn
image: /static/templates/video-generation.png
details: <h1>Label exact products on the shelves</h1>
config: |
  <View>
    <Header value="Input Image and Audio" />
    <Image name="image" value="$image"/>
    <Audio name="audio_1" value="$audio" zoom="true" hotkey="ctrl+enter" />

    <Header value="Generated Video" />
    <Video name="video" value="$video_url" sync="audio"/>
    <Audio name="audio" value="$video_url" sync="video" speed="false"/>

    <Rating name="rating" toName="video" maxRating="10" icon="star" size="medium" />
  </View>
 
